-- /projects/project_Full-stack/egyPyramidDashbord/backend/egyDashbordApi/database/schema.sql
-- users


-- medias
create table public.medias (
    id bigint generated by default as identity not null,
    tmdb_id text null,
    title text not null,
    story text null,
    poster_url text null,
    category text not null,
    year text not null,
    rating text null,
    created_at timestamp with time zone not null default now(),
    labels text null,
    runtime text null,
    updated_at timestamp with time zone not null default now(),
    duration_iso text null,
    media_type text not null default 'movie'::text,
    is_ready boolean not null default false,
    is_notified boolean not null default false,
    is_facebook_posted boolean not null default false,
    facebook_posted_at timestamp with time zone null,
    normalized_title text not null,
    slug text not null,
    constraint medias_pkey primary key (id),
    constraint medias_slug_key1 unique (slug),
    constraint medias_tmdb_id_key unique (tmdb_id),
    constraint check_category check (
        (category = any (array['tv'::text, 'movie'::text]))
    ),
    constraint check_media_type check (
        (
        media_type = any (array['movie'::text, 'series'::text])
        )
    ),
    constraint medias_media_type_check check (
        (
        media_type = any (array['movie'::text, 'series'::text, 'tv'::text])
        )
    )
) TABLESPACE pg_default;

create unique INDEX IF not exists unique_normalized_year on public.medias using btree (normalized_title, year) TABLESPACE pg_default;

create index IF not exists idx_medias_norm on public.medias using btree (normalized_title) TABLESPACE pg_default;

create unique INDEX IF not exists medias_slug_key on public.medias using btree (slug) TABLESPACE pg_default;

create unique INDEX IF not exists unique_title_year_ci on public.medias using btree (lower(title), year) TABLESPACE pg_default;

create trigger enforce_is_ready BEFORE INSERT
or
update OF is_ready,
story,
poster_url on medias for EACH row
execute FUNCTION trg_enforce_is_ready ();

create trigger trg_set_normalized BEFORE INSERT
or
update OF title,
year on medias for EACH row
execute FUNCTION set_normalized_title ();

-- seasons
create table public.seasons (
    id bigint generated by default as identity not null,
    media_id bigint not null,
    season_number integer not null,
    created_at timestamp with time zone not null default now(),
    constraint seasons_pkey primary key (id),
    constraint unique_season_media unique (id, media_id),
    constraint unique_season_per_media unique (media_id, season_number),
    constraint seasons_media_id_fkey foreign KEY (media_id) references medias (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists idx_seasons_media_id on public.seasons using btree (media_id) TABLESPACE pg_default;

-- episodes
create table public.episodes (
    id bigint generated by default as identity not null,
    media_id bigint not null,
    episode_number integer not null,
    identifier text not null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    status_message text not null default 'Waiting...'::text,
    progress_percent integer not null default 0,
    download_speed text not null default '0 MB/s'::text,
    status text not null default 'idle'::text,
    download_url text null,
    season_id bigint null,
    slug text null,
    constraint episodes_pkey primary key (id),
    constraint episodes_identifier_key unique (identifier),
    constraint episodes_media_id_fkey foreign KEY (media_id) references medias (id) on delete CASCADE,
    constraint episodes_season_id_fkey foreign KEY (season_id) references seasons (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists idx_episodes_media_id on public.episodes using btree (media_id) TABLESPACE pg_default;

create index IF not exists idx_episodes_season_id on public.episodes using btree (season_id) TABLESPACE pg_default;

create unique INDEX IF not exists unique_movie_episode on public.episodes using btree (media_id, episode_number) TABLESPACE pg_default
where
    (season_id is null);

create unique INDEX IF not exists unique_series_episode on public.episodes using btree (media_id, season_id, episode_number) TABLESPACE pg_default
where
    (season_id is not null);

create trigger tr_auto_generate_identifier BEFORE INSERT on episodes for EACH row
execute FUNCTION generate_episode_identifier ();

-- links
create table public.links (
    id bigint generated by default as identity not null,
    episode_id bigint not null,
    server_name text not null,
    url text not null,
    created_at timestamp with time zone not null default now(),
    link_type text not null default 'watch'::text,
    quality text not null default '720p'::text,
    last_check_status text null default 'pending'::text,
    last_check_at timestamp with time zone null,
    error_message text null,
    check_count integer not null default 0,
    is_fixed boolean not null default false,
    last_success_at timestamp with time zone null,
    old_url text null,
    constraint links_pkey primary key (id),
    constraint unique_episode_server unique (episode_id, server_name),
    constraint links_episode_id_fkey foreign KEY (episode_id) references episodes (id) on delete CASCADE,
    constraint links_link_type_check check (
        (
        link_type = any (array['watch'::text, 'download'::text])
        )
    )
) TABLESPACE pg_default;

create index IF not exists idx_links_episode_id on public.links using btree (episode_id) TABLESPACE pg_default;

create index IF not exists idx_links_last_check_status on public.links using btree (last_check_status) TABLESPACE pg_default;

create index IF not exists idx_links_server_lower on public.links using btree (lower(server_name)) TABLESPACE pg_default;

create trigger auto_check_on_link_insert
after INSERT on links for EACH row
execute FUNCTION trg_after_link_change ();

create trigger auto_unready_on_link_delete
after DELETE on links for EACH row
execute FUNCTION trg_after_link_change ();

-- genres
create table public.genres (
    id bigint generated by default as identity not null,
    name text not null,
    slug text not null,
    created_at timestamp with time zone not null default now(),
    constraint genres_pkey primary key (id),
    constraint genres_name_key unique (name),
    constraint genres_slug_key unique (slug)
) TABLESPACE pg_default;

-- media_genres
create table public.media_genres (
    media_id bigint not null,
    genre_id bigint not null,
    constraint media_genres_pkey primary key (media_id, genre_id),
    constraint media_genres_genre_id_fkey foreign KEY (genre_id) references genres (id) on delete CASCADE,
    constraint media_genres_media_id_fkey foreign KEY (media_id) references medias (id) on delete CASCADE
) TABLESPACE pg_default;

-- label_translations


-- download_tasks
create table public.download_tasks (
    id bigint generated by default as identity not null,
    task_name text not null,
    source_url text not null,
    status text not null default 'idle'::text,
    progress_percent integer not null default 0,
    download_speed text not null default '0 MB/s'::text,
    status_message text not null default 'Waiting...'::text,
    created_at timestamp with time zone not null default now(),
    is_cancelled boolean not null default false,
    trailer_url text null,
    normalized_task_name text not null,
    task_year text null,
    fallback_urls text[] null,
    constraint download_tasks_pkey primary key (id),
    constraint download_tasks_task_name_key unique (task_name)
) TABLESPACE pg_default;

create unique INDEX IF not exists unique_task_norm_year on public.download_tasks using btree (normalized_task_name, task_year) TABLESPACE pg_default;

create index IF not exists idx_download_tasks_status on public.download_tasks using btree (status) TABLESPACE pg_default;

create trigger fill_task_norm BEFORE INSERT
or
update OF task_name on download_tasks for EACH row
execute FUNCTION trg_fill_task_norm ();